version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: form-builder-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: formbuilder
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - form-builder-network

volumes:
  mongodb_data:

networks:
  form-builder-network:
    driver: bridge